### ISSUE TITLE
please tag 1.0.3 as a release

### ISSUE THREAD

**Issue by elijah** [anchor/nagios-plugin-elasticsearch#29]
Hey hey,

You updated the metadata for 1.0.3 but didn't tag a release - can you do that?  I'm fighting this battle against pip over here too -- and this is a point of some breakage.  :)  

best,

--e

**Comment by fractalcat** [comment]
1.0.3 should actually have been 1.1.0 - I must have been distracted when I merged something. I've tagged and released v1.1.0; hopefully this serves to solve your breakage.
